In [1]:
! pip install numpy

In [2]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
## Reshape

In [11]:
arr.reshape(1,4)
print(arr.shape)

(4,)


In [12]:
# Range

In [22]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

# Ones

In [25]:
np.ones(5).reshape(5,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

# zeros

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Identity matrix

In [30]:
a = np.eye(4)

In [31]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
int(a[3][3])

1