In [84]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
## Reshape

In [11]:
arr.reshape(1,4)
print(arr.shape)

(4,)


In [12]:
# Range

In [22]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

# Ones

In [25]:
np.ones(5).reshape(5,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

# zeros

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Identity matrix

In [30]:
a = np.eye(4)

In [31]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
int(a[3][3])

1

In [39]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int64


Numpy vectorized Operation

In [52]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,33,42,51])


In [51]:
# Elementwise addition
print('Addition :',arr1+arr2)

# Elementwise Substraction
print('Addition :',arr1-arr2)

# Elementwise Multiplication
print('Addition :',arr1*arr2)

# Elementwise substitution
print('Addition :',arr2/arr1)

Addition : [11 22 33 44 55]
Addition : [ -9 -18 -27 -36 -45]
Addition : [ 10  40  90 160 250]
Addition : [10. 10. 10. 10. 10.]


In [56]:
# Universal functions

# SQRT
arr = np.array([1,2,3])
print(f'Square root : {np.sqrt(arr)}')

# Exponantial 
print(f'Exponantial : {np.exp(arr)}')

# Sine
print(f'Sine : {np.sin(arr)}')

# Natural log
print(f'Natural log : {np.log(arr)}')



Square root : [1.         1.41421356 1.73205081]
Exponantial : [ 2.71828183  7.3890561  20.08553692]
Sine : [0.84147098 0.90929743 0.14112001]
Natural log : [0.         0.69314718 1.09861229]


Array Slicing and indexing 

In [73]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [74]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
arr[]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [70]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [72]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

# Statistical concept 

In [83]:
# Normalization
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)
normalized = (data-mean)/std

print(f'Normalizeed Data : {normalized}')

Normalizeed Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# 