In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
## Reshape

In [4]:
arr.reshape(1,4)
print(arr.shape)

(4,)


In [5]:
# Range

In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

# Ones

In [7]:
np.ones(5).reshape(5,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

# zeros

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Identity matrix

In [9]:
a = np.eye(4)

In [10]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
int(a[3][3])

1

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int64


Numpy vectorized Operation

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,33,42,51])


In [14]:
# Elementwise addition
print('Addition :',arr1+arr2)

# Elementwise Substraction
print('Addition :',arr1-arr2)

# Elementwise Multiplication
print('Addition :',arr1*arr2)

# Elementwise substitution
print('Addition :',arr2/arr1)

Addition : [11 22 36 46 56]
Addition : [ -9 -18 -30 -38 -46]
Addition : [ 10  40  99 168 255]
Addition : [10.  10.  11.  10.5 10.2]


In [15]:
# Universal functions

# SQRT
arr = np.array([1,2,3])
print(f'Square root : {np.sqrt(arr)}')

# Exponantial 
print(f'Exponantial : {np.exp(arr)}')

# Sine
print(f'Sine : {np.sin(arr)}')

# Natural log
print(f'Natural log : {np.log(arr)}')



Square root : [1.         1.41421356 1.73205081]
Exponantial : [ 2.71828183  7.3890561  20.08553692]
Sine : [0.84147098 0.90929743 0.14112001]
Natural log : [0.         0.69314718 1.09861229]


Array Slicing and indexing 

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [17]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [19]:
arr[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

# Statistical concept 

In [20]:
# Normalization
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)
normalized = (data-mean)/std

print(f'Normalizeed Data : {normalized}')

Normalizeed Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
